### ISSUE TITLE
PoF issue with equal bids for lowest, and set sizes equal to bidders

### ISSUE THREAD

**Issue by 0o-de-lally** [0LNetworkCommunity/libra-framework#251]
# Problem

Currently, there is no mechanism to promote bid competition among validators for the seats auction in Proof of Fee. All eligible validators eventually enter the validator set regardless of their bid amount.

# Current Snapshot/Context

In epoch 90, we had 16 validators in the set with the same minimum bid of 1%. Without a competition mechanism, there is no reason for them to change their bids.

# Initially Proposed Approach in this Issue

Starting with 40 available seats, remove x seats, where x is a random number between 0 and 4 (10% of 40). With this approach, the number of available seats will tend to decrease over epochs. This is because the number only increases by one if all nodes behave well, and there is a 1/5 chance that x will be zero.

# Alternative Approach

To provoke competition among validators when the validator set surpasses the boot-up threshold of 20 compliant validators, the validator set size will be defined by the minimum value between:
 1. Musical Chairs suggestion, and
 2. 90% of qualified bidders

This percentage is experimental and may be adjusted after observing real-world performance. It could also be dynamic, based on another function or randomized within a range, as initially proposed.

# Impact on Current Seats Auction

Assuming all 36 validators are compliant in the current epoch and remain the same qualified bidders, we should expect the size for the next epoch to be 33, leaving out the 3 validators with the lowest bids.

If multiple validators have the same lowest bid amount, they will be randomly picked by shuffling their positions after sorting by bid.

Example: The last 3 validators (0x1, 0x2, 0x3) have the lowest bid of 1%, and 2 will be out of the set according to the new rule above. We will shuffle their positions (0x3, 0x1, 0x2) to ensure fairness when picking the one to be in the validator set.

# Advantages of the Alternative Approach

- **Consistent Competition**: Ensures continuous competition, encouraging validators to regularly review and increase their bids.
- **Dynamic Adaptation**: Adapts the number of seats to the current bid landscape, promoting a responsive and competitive validator set.
- **Fairness and Transparency**: Resolves issue #271 by ensuring fairness and transparency, avoiding potential biases and manipulations.
- **Higher Stakes for Validators**: Motivates validators to commit more resources to stay in the set, leading to a more secure and robust network.

**Comment by soaresa** [comment]
WIP

# Problem

Currently, there is no mechanism implemented to promote bid competition among validators for the seats auction in Proof of Fee. All eligible validators eventually enter the validator set regardless of their bid amount.

# Current Snapshot/Context

In epoch 90, we have 16 validators in the set, all with the same minimum bid of 10 Libra. Without competition, there is no technical reason for them to change their bids. Validators with higher bids could use the vouch system to exclude validators with bids below an arbitrary threshold.

# Initially Proposed Approach in this Issue

Starting with 40 available seats, remove x seats, where x is a random number between 0 and 4 (10% of 40). With this approach, the number of available seats will tend to decrease over epochs. This is because the number only increases by one if all nodes behave well, and there is a 1/5 chance that x will be zero.

# Alternative Approach

To provoke competition among validators when bids are unfavorable for the network, we can use a specific criterion. This competition can be triggered when the reward for the next epoch exceeds 3 to 5 times the average bid, as mentioned in the PoF part 2 article.

The competition would involve removing 10% of the eligible validator seats, causing those with the lowest bids to be excluded from the epoch. These validators would need to reconsider their bidding strategy to rejoin the set in the following epoch.

Once bids are out of the competition zone, seats will no longer be removed, accommodating all validators according to other rules, such as those of musical chairs.

**Note**: For this implementation, issue Y must be resolved to ensure fairness in random positioning among validators with the same bid amount, so those selected to be part of the set are chosen randomly.

# Impact on Current Seats Auction

In epoch 90, we had 38 eligible validators with an average bid (AB) of ~170 and a base reward (BR) of ~6,525. Sixteen validators have the same minimum bid of 10 Libra, resulting in a BR/AB ratio of ~38.

Since BR/AB > 3, we will reduce the number of available seats by 10%. If all 38 validators behave as expected, epoch 91 would have 38 available seats. Thus, 10% of the seats (rounded down to 3) will be removed, leaving 35 seats. In this scenario, the 16 validators with the lowest bids will compete for the remaining 13 seats, with an 18.75% probability of being excluded from the next set.

If all validators have distinct bids, the 3 validators with the lowest bids will be 100% excluded from the set. If only 2 validators have the same bid amount as the third lowest, each would have a 50% chance of being excluded.

# Advantages of the Alternative Approach

- **Consistent Competition**: Ensures continuous competition, encouraging validators to regularly review and increase their bids.
- **Dynamic Adaptation**: Adapts the number of seats to the current bid landscape, promoting a responsive and competitive validator set.
- **Fairness and Transparency**: Resolving issue Y ensures fairness and transparency, avoiding potential biases and manipulations.
- **Higher Stakes for Validators**: Motivates validators to commit more resources to stay in the set, leading to a more secure and robust network.

**Comment by 0o-de-lally** [comment]
TODO: deduplicate bubble sort and make own module.
